/* RFC 3161 timestamping — DER build + light verify, and the anchor surface that
   attaches/re-derives an attested time. No public network: the TSA round-trip is
   served by a throwaway localhost server, so the REAL attachTimestamp path runs.
   The REQ_HEX / TOK_B64 / CP_DIGEST constants are produced by the Python package
   (timestamp.py / anchor.py) — asserting against them proves the two
   implementations are byte-identical, so a token minted by one verifies in the
   other. */

import { test } from "node:test";
import assert from "node:assert/strict";
import { createServer, type Server } from "node:http";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  buildRequest, requestToken, verify, messageImprint, derInt, tlv, MAX_TSA_RESPONSE,
} from "../src/timestamp.ts";
import {
  checkpoint, checkpointDigest, attachTimestamp, checkpointVerifiedTime,
  verifyCompleteness, TimestampError, type Checkpoint,
} from "../src/anchor.ts";
import { build, Recorder } from "../src/record.ts";
import { readLog } from "../src/verify.ts";

// --- cross-language parity fixtures (generated by the Python package) --------
const PY_REQ_HEX =
  "30390201013031300d060960864801650304020105000420" + "ab".repeat(32) + "0101ff";
const PY_TOKEN_B64 =
  "MIIBAGNtcy1wcmVmaXgwMTANBglghkgBZQMEAgEFAAQgzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc0CAhCSGA8yMDI2MDcyMzE0NTk1OVpzaWduYXR1cmUtdGFpbA==";
const PY_CP_DIGEST = "2889eb2fb64fb868351d162d6f04bf0a6cfe18fe16b780e56a04940aec738387";

/* The Python _fake_token shape, rebuilt in TS: <DER prefix> messageImprint
   serialNumber genTime <tail> — enough for verify() to walk. */
function fakeToken(digestHex: string, gen = "20260723145959Z"): Buffer {
  return Buffer.concat([
    Buffer.from([0x30, 0x82, 0x01, 0x00]),
    Buffer.from("cms-prefix"),
    messageImprint(Buffer.from(digestHex, "hex")),
    derInt(4242),
    tlv(0x18, Buffer.from(gen)),
    Buffer.from("signature-tail"),
  ]);
}

/* Spin a localhost TSA that replies with `body` (or a per-request body), returns
   its URL, and a close(). No public network is touched. */
async function tsaServer(handler: () => Buffer | null): Promise<{ url: string; close: () => void }> {
  const server: Server = createServer((_req, res) => {
    const body = handler();
    if (body === null) { res.destroy(); return; }
    res.writeHead(200, { "Content-Type": "application/timestamp-reply" });
    res.end(body);
  });
  await new Promise<void>((r) => server.listen(0, "127.0.0.1", r));
  const { port } = server.address() as { port: number };
  return { url: `http://127.0.0.1:${port}/tsr`, close: () => server.close() };
}

test("timestamp: DER request is byte-identical to the Python build", () => {
  const req = buildRequest(Buffer.from("ab".repeat(32), "hex"));
  assert.equal(req.toString("hex"), PY_REQ_HEX);
  assert.equal(req[0], 0x30);
  assert.ok(req.includes(messageImprint(Buffer.from("ab".repeat(32), "hex"))));
});

test("timestamp: verify reads a Python-minted token and matches its digest+time", () => {
  const res = verify(Buffer.from(PY_TOKEN_B64, "base64"), "cd".repeat(32));
  assert.equal(res.imprint_ok, true);
  assert.equal(res.gen_time, "2026-07-23T14:59:59Z");
});

test("timestamp: verify rejects a token minted for someone else's chain", () => {
  const res = verify(fakeToken("cd".repeat(32)), "ef".repeat(32));
  assert.equal(res.imprint_ok, false);
  assert.equal(res.gen_time, null);
});

test("checkpointDigest excludes self-asserted ts/tsa and matches Python", () => {
  const cp = { chain_root: "r", subject: "acme", count: 2, head: "h", ts: "2026-01-01T00:00:00Z" } as Checkpoint;
  const backdated = { ...cp, ts: "2099-01-01T00:00:00Z", tsa: { url: "x" } as never };
  assert.equal(checkpointDigest(cp), checkpointDigest(backdated));
  assert.equal(checkpointDigest(cp), PY_CP_DIGEST);
});

test("attachTimestamp binds the checkpoint's state digest (real HTTP path)", async () => {
  const cp: Checkpoint = { chain_root: "r", subject: "acme", count: 2, head: "h", ts: "t" };
  const dig = checkpointDigest(cp);
  const srv = await tsaServer(() => fakeToken(dig, "20260101000000Z"));
  try {
    const out = await attachTimestamp(cp, srv.url);
    assert.equal(out.tsa?.gen_time, "2026-01-01T00:00:00Z");
    assert.equal(out.tsa?.digest, dig);
    assert.ok(out.tsa?.token_b64);
  } finally { srv.close(); }
});

test("attachTimestamp rejects a token that does not cover the checkpoint", async () => {
  const cp: Checkpoint = { chain_root: "r", subject: "s", count: 1, head: "h", ts: "t" };
  const srv = await tsaServer(() => fakeToken("ff".repeat(32)));
  try {
    await assert.rejects(attachTimestamp(cp, srv.url), TimestampError);
  } finally { srv.close(); }
});

test("attachTimestamp rejects (does not lose the checkpoint) on TSA failure", async () => {
  const cp: Checkpoint = { chain_root: "r", subject: "s", count: 1, head: "h", ts: "t" };
  const srv = await tsaServer(() => null); // socket destroyed → network error
  try {
    await assert.rejects(attachTimestamp(cp, srv.url), TimestampError);
  } finally { srv.close(); }
});

test("checkpointVerifiedTime re-derives from the token, ignoring the editable field", () => {
  const cp: Checkpoint = { chain_root: "r", subject: "acme", count: 2, head: "h", ts: "t" };
  const dig = checkpointDigest(cp);
  cp.tsa = {
    url: "u", digest: dig,
    gen_time: "2099-01-01T00:00:00Z", // FORGED cache field
    token_b64: fakeToken(dig, "20260101000000Z").toString("base64"),
  };
  assert.equal(checkpointVerifiedTime(cp), "2026-01-01T00:00:00Z"); // from the token
  cp.tsa.token_b64 = Buffer.from("not-a-token").toString("base64"); // garbage
  assert.equal(checkpointVerifiedTime(cp), null); // cannot fabricate a time
});

test("verifyCompleteness reports token-derived time, not the forged JSON field", () => {
  const dir = mkdtempSync(join(tmpdir(), "halo-ts-"));
  try {
    const path = join(dir, "c.jsonl");
    new Recorder(path).append(build("tool_call", "security", { tool: "a", subject: "acme" }));
    const records = readLog(path);
    const cp = checkpoint(records);
    const dig = checkpointDigest(cp);
    cp.tsa = {
      url: "u", digest: dig,
      gen_time: "2099-01-01T00:00:00Z", // operator edits this
      token_b64: fakeToken(dig, "20260101000000Z").toString("base64"),
    };
    const res = verifyCompleteness(records, [cp]);
    assert.equal(res.ok, true);
    assert.equal(res.tsa_time, "2026-01-01T00:00:00Z"); // token, not the edit
    assert.equal(res.tsa_unverified, undefined);
  } finally { rmSync(dir, { recursive: true, force: true }); }
});

test("requestToken caps an oversized TSA response", async () => {
  const srv = await tsaServer(() => Buffer.alloc(MAX_TSA_RESPONSE + 1024));
  try {
    await assert.rejects(requestToken("ab".repeat(32), srv.url), /exceeds/);
  } finally { srv.close(); }
});
